default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['WAREHOUSE_DATABASE_PASSWORD'] %>'] %>

development:
  <<: *default
  database: warehouse-development

test:
  <<: *default
  database: warehouse-test

production:
  <<: *default
  database: warehouse-production

