x-app:
  &app
  build:
    context: .
    args:
      RUBY_VERSION: '2.6.8'
      PG_MAJOR: '12'
      NODE_MAJOR: '12'
      YARN_VERSION: '1.22.17'
      BUNDLER_VERSION: '1.3.0'
  image: warehouse-back:1.0.0
  environment:
    &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    - /tmp
    - /backend/tmp/pids

x-backend:
  &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/backend:cached
    - bundle:/usr/local/bundle
    - rails_cache:/backend/tmp/cache
    - node_modules:/backend/node_modules
    - history:/usr/local/hist
    - ./.psqlrc:/root/.psqlrc:ro
  environment:
    &backend_environment
    <<: *env
    REDIS_URL: redis://redis:6379/
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /backend/tmp/caches
    YARN_CACHE_FOLDER: /backend/node_modules/.yarn-cache
    PSQL_HISTFILE: /usr/local/hist/.psql_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
  depends_on:
    &backend_depends_on
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  rails:
    <<: *backend
    command: rails s
  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      sidekiq:
        condition: service_started
  front:
    build:
      context: ../../frontend
    volumes:
      - .:/frontend
    ports:
      - 3006:3006
    image: app:react
    container_name: react_container
    command: npm start
  sidekiq:
    <<: *backend
    command: bundle exec sidekiq

  postgres:
    image: postgres:12
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - history:/user/local/hist
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_PASSWORD: ${WAREHOUSE_DATABASE_PASSWORD:-postgres}
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U ${DATABASE_USER:-postgres} -h 127.0.0.1
      interval: 5s

  redis:
    image: 'redis:7-alpine'
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30


volumes:
  bundle:
  history:
  rails_cache:
  node_modules:
  postgres:
  redis:
  packs:
  packs-test:
  frontend:
